name: Node.js CI/CD with Docker

on:
  push:
    branches:
      - main
jobs:
  nodejs-cicd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd projects/nodejs-cicd-pipeline/
          npm install

      - name: Build Docker image
        run: |
          cd projects/nodejs-cicd-pipeline/
          docker build -t node-demo:${{ github.sha }} .

      - name: Run tests
        run: |
          cd projects/nodejs-cicd-pipeline/  
          # Run tests here, replace with your actual test commands
          echo "TODO: Run test here"

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd projects/nodejs-cicd-pipeline/
          npx semantic-release

      # - name: Push Docker image
      #   run: |
      #     # Check if the branch is main and push image if true
      #     if [ ${{ github.ref }} != 'refs/heads/main' ]; then
      #       echo "Skip push image for ${{ github.ref }}"
      #       exit 0
      #     else
      #       docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      #       docker tag node-demo:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/node-demo:${{ github.sha }}
      #       docker images
      #       docker push ${{ secrets.DOCKERHUB_USERNAME }}/node-demo:${{ github.sha }}
      #     fi
